apiVersion: v1
kind: Pod
metadata:
  name: example-pod
#Pod specifications
spec:
  # Multiple containers can be used in a pod
  containers:
  # Container that has a configmap as environment variables
  - name: config-env-container
    image: redis
    env:
      - name: PROJECT_NAME # Environment variable name
        valueFrom:
          configMapKeyRef:
            name: my-config # ConfigMap name
            key: project-name # Key in ConfigMap
  # A container that would mount the config map example
  - name: config-map-volume-container
    image: nginx
    # Normal volume mounting like docker
    # This is now specific for config maps
    volumeMounts:
      - name: config
        mountPath: "/etc/test/foo"
        # VERY important for ConfigMap Volumes
        readOnly: true
  volumes: 
    - name: config
      configMap:
        name: my-config